"""Day 5: Add GateExecutionHistory table

Revision ID: 2a05cdeeb5da
Revises: f4d2372225aa
Create Date: 2026-03-01 22:34:56.593276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a05cdeeb5da"
down_revision: Union[str, None] = "f4d2372225aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
