"""Day 3: Add Reservation, Stay, RatePlan, Charge tables

Revision ID: 32557f7b55f8
Revises: 1574847754ef
Create Date: 2026-02-22 11:53:57.851788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32557f7b55f8"
down_revision: Union[str, None] = "1574847754ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)
    existing = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if "rate_plans" not in existing:
        op.create_table(
            "rate_plans",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("property_id", sa.Integer(), nullable=False),
            sa.Column("room_type_id", sa.Integer(), nullable=False),
            sa.Column("supersedes_id", sa.Integer(), nullable=True),
            sa.Column("superseded_by_id", sa.Integer(), nullable=True),
            sa.Column("code", sa.String(length=50), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("base_rate", sa.Numeric(precision=10, scale=2), nullable=False),
            sa.Column("weekend_rate", sa.Numeric(precision=10, scale=2), nullable=True),
            sa.Column("valid_from", sa.Date(), nullable=False),
            sa.Column("valid_to", sa.Date(), nullable=True),
            sa.Column("min_length_of_stay", sa.Integer(), nullable=False),
            sa.Column("max_length_of_stay", sa.Integer(), nullable=True),
            sa.Column("min_advance_booking", sa.Integer(), nullable=False),
            sa.Column("max_advance_booking", sa.Integer(), nullable=True),
            sa.Column("valid_days_of_week", sa.String(length=20), nullable=True),
            sa.Column("has_blackout_dates", sa.Boolean(), nullable=False),
            sa.Column("blackout_dates", sa.Text(), nullable=True),
            sa.Column("cancellation_policy", sa.String(length=50), nullable=True),
            sa.Column("cancellation_hours", sa.Integer(), nullable=True),
            sa.Column(
                "cancellation_fee_percent",
                sa.Numeric(precision=5, scale=2),
                nullable=True,
            ),
            sa.Column("is_public", sa.Boolean(), nullable=False),
            sa.Column("is_corporate", sa.Boolean(), nullable=False),
            sa.Column("is_government", sa.Boolean(), nullable=False),
            sa.Column("is_loyalty", sa.Boolean(), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("is_superseded", sa.Boolean(), nullable=False),
            sa.Column("version", sa.Integer(), nullable=False),
            sa.Column("effective_date", sa.Date(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("created_by", sa.String(length=100), nullable=True),
            sa.ForeignKeyConstraint(
                ["property_id"],
                ["properties.id"],
            ),
            sa.ForeignKeyConstraint(
                ["room_type_id"],
                ["room_types.id"],
            ),
            sa.ForeignKeyConstraint(
                ["supersedes_id"],
                ["rate_plans.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_rate_plans_code"), "rate_plans", ["code"], unique=False
        )
        op.create_index(op.f("ix_rate_plans_id"), "rate_plans", ["id"], unique=False)
        op.create_index(
            op.f("ix_rate_plans_is_active"), "rate_plans", ["is_active"], unique=False
        )
        op.create_index(
            op.f("ix_rate_plans_is_superseded"),
            "rate_plans",
            ["is_superseded"],
            unique=False,
        )
        op.create_index(
            op.f("ix_rate_plans_property_id"),
            "rate_plans",
            ["property_id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_rate_plans_room_type_id"),
            "rate_plans",
            ["room_type_id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_rate_plans_superseded_by_id"),
            "rate_plans",
            ["superseded_by_id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_rate_plans_supersedes_id"),
            "rate_plans",
            ["supersedes_id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_rate_plans_valid_from"), "rate_plans", ["valid_from"], unique=False
        )
        op.create_index(
            op.f("ix_rate_plans_valid_to"), "rate_plans", ["valid_to"], unique=False
        )
        op.add_column(
            "room_types", sa.Column("property_id", sa.Integer(), nullable=True)
        )
        op.add_column(
            "room_types", sa.Column("max_adults", sa.Integer(), nullable=True)
        )
        op.add_column(
            "room_types", sa.Column("max_children", sa.Integer(), nullable=True)
        )
        op.add_column(
            "room_types", sa.Column("bed_type", sa.String(length=50), nullable=True)
        )
        op.add_column("room_types", sa.Column("num_beds", sa.Integer(), nullable=True))
        op.add_column("room_types", sa.Column("size_sqft", sa.Integer(), nullable=True))
        op.create_index(
            op.f("ix_room_types_property_id"),
            "room_types",
            ["property_id"],
            unique=False,
        )
        op.add_column("rooms", sa.Column("room_type_id", sa.Integer(), nullable=True))
        op.add_column(
            "rooms", sa.Column("room_number", sa.String(length=10), nullable=True)
        )
        op.add_column(
            "rooms", sa.Column("building", sa.String(length=50), nullable=True)
        )
        op.add_column(
            "rooms", sa.Column("occupancy_changed_at", sa.DateTime(), nullable=True)
        )
        op.add_column(
            "rooms", sa.Column("condition_changed_at", sa.DateTime(), nullable=True)
        )
        op.add_column("rooms", sa.Column("notes", sa.Text(), nullable=True))
        # ### end Alembic commands ###


def downgrade() -> None:
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)

    def safe_drop_index(index_name, table_name):
        try:
            indexes = [i["name"] for i in inspector.get_indexes(table_name)]
            if index_name in indexes:
                op.drop_index(index_name, table_name=table_name)
        except Exception:
            pass

    def safe_drop_table(table_name):
        try:
            if table_name in inspector.get_table_names():
                op.drop_table(table_name)
        except Exception:
            pass

    def safe_drop_column(table_name, column_name):
        try:
            cols = [c["name"] for c in inspector.get_columns(table_name)]
            if column_name in cols:
                with op.batch_alter_table(table_name) as batch_op:
                    batch_op.drop_column(column_name)
        except Exception:
            pass

    safe_drop_table("charges")
    safe_drop_table("stays")
    safe_drop_table("reservations")
    safe_drop_table("rate_plans")
    safe_drop_column("rooms", "room_type_id")
    safe_drop_table("room_types")
