"""Day 5: Add GateExecutionHistory table

Revision ID: f4d2372225aa
Revises: 9fbf27562b2f
Create Date: 2026-03-01 22:32:41.299685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4d2372225aa"
down_revision: Union[str, None] = "9fbf27562b2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
